linters-settings:
  funlen:
    lines: 100
    statements: 450
  golint:
    min-confidence: 0
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  lll:
    line-length: 80
    tab-width: 4
  maligned:
    suggest-new: true
  misspell:
    locale: US
  paralleltest:
    ignore-missing: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

issues:
  exclude:
    - Using the variable on range scope `tt` in function literal
    - Using the variable on range scope `tc` in function literal
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - funlen
        - dupl
    - source: "^//go:generate "
      linters:
        - lll
    - source: "`env:"
      linters:
        - lll
    - source: "`json:"
      linters:
        - lll
    - source: "`xml:"
      linters:
        - lll
    - source: "`yaml:"
      linters:
        - lll

run:
  timeout: 2m
  allow-parallel-runners: true
  modules-download-mode: readonly
